### ISSUE TITLE
Add SkateJS to list of libraries.

### ISSUE THREAD

**Issue by treshugart** [ericelliott/essential-javascript-links#19]
[SkateJS](https://github.com/skatejs/skatejs)

I'd PR this, but there's a couple sections where you could put it: Libraries or Web components (custom elements, more specifically). I'm assuming the latter is more general information, though.

Thanks for considering it. Cheers!

**Comment by ericelliott** [comment]
I love the idea of a better API for creating custom elements, but I'm not sure this is it.

**Comment by treshugart** [comment]
It's a dagger through my heart, but fair. Mind elaborating?

**Comment by ericelliott** [comment]
It's a good start, but...The API is still too complex, calls for constructors (constructors are obnoxious), doesn't suggest a good interface for composing components, lacks automatic event delegation... I could probably go on, but I'm sleepy. :)

**Comment by treshugart** [comment]
I get it. I asked to be featured and you didn't like it. That's cool! It's a subjective listing and people are entitled to have differing opinions. That said, I feel compelled to correct some misconceptions in case any others wander along here.

- Composition is nice to have, I agree. Skate is declarative first because web components are, too. It maps better to the minds of those familiar with native custom elements. It's not there yet, but we're working on making it more composable.
- Constructors are optional. They're there because the spec wants them and Skate likes the spec (I should make them callable without the "new" operator, though). Regardless, there's several other supported ways to construct a custom element if you don't like constructors.
- Event delegation *is* automatic. It doesn't use it if you don't specify a selector because it's not necessary.

I appreciate your feedback, and I will take it to heart. However, your last statement "I could probably go on, but I'm sleepy" seems dismissive and aloof. Whether you meant it that way or not, I'll remind you that I am a human being on the other end of this discussion.

All the best, mate, and thanks again for your consideration.

**Comment by ericelliott** [comment]
Sounds like I offended you a little. Let me clarify. I think the library is *cool*.

> Constructors are optional. They're there because the spec wants them and Skate likes the spec (I should make them callable without the "new" operator, though). Regardless, there's several other supported ways to construct a custom element if you don't like constructors.

Cool. Maybe docs and examples could clarify that, and de-emphasize constructor use?

> Event delegation is automatic. It doesn't use it if you don't specify a selector because it's not necessary.

It sounds like we're not on the same page about the meaning of "automatic" -- in my mind, it means that any event listeners attached to a child node should be auto-delegated to the root node *without needing a selector.* Since the child node was specifically targeted, you don't need a selector to target it. I haven't looked at the code, but you may need an extra layer of abstraction to accomplish that.

I realize that may be out-of-scope for what you're trying to do with this lib, but now that I've tasted the advantages, it would be tough to go back. In case you're not familiar, check out [how this is handled by React](https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#under-the-hood-autobinding-and-event-delegation).

It seems like this lib is a lower-level abstraction than that, which is OK, but maybe not what developers really need to work with directly to build today's complex UIs...

> "I could probably go on, but I'm sleepy" seems dismissive and aloof.

It certainly wasn't intended that way. I was sleepy, and there were already enough red marks to disqualify the library from being an **essential resource that all JS devs should be aware of**, in my opinion.

That's the bar here. I admit it's imperfect. I'm a real human being too, flaws and all. I think what you're doing with the lib is cool, and if you can make some improvements in the documentation (like, clarify and emphasize the features you pointed out above), figure out element composition, and gain a bit more traction, the library has the *potential* to earn a spot on the list.

**Comment by treshugart** [comment]
> It sounds like we're not on the same page about the meaning of "automatic" -- in my mind, it means that any event listeners attached to a child node should be auto-delegated to the root node without needing a selector. Since the child node was specifically targeted, you don't need a selector to target it. I haven't looked at the code, but you may need an extra layer of abstraction to accomplish that.

I'm not 100% clear what you mean, but I take "specifically targeted" to be `<Element onEvent={this.handler}>`. If that's correct, then you're right in saying that it's a lower-level abstraction - at least in this sense - but that's by design so any templating / data-binding layer can be dropped in. I do like the idea of doing events like that, but it might be too opinionated. I'll have a play and see how it goes.

> It certainly wasn't intended that way. I was sleepy, and there were already enough red marks to disqualify the library from being an essential resource that all JS devs should be aware of, in my opinion.

I'm content with that and your opinion was not offensive; not everyone has to like everything. I apologise for interpreting that statement to be malicious. Again, thanks for your input.

**Comment by ericelliott** [comment]
> I'm not 100% clear what you mean, but I take "specifically targeted" to be <Element onEvent={this.handler}>. If that's correct, then you're right in saying that it's a lower-level abstraction - at least in this sense - but that's by design so any templating / data-binding layer can be dropped in. I do like the idea of doing events like that, but it might be too opinionated. I'll have a play and see how it goes.

Maybe it could be done in a separate module that plays nice with this lib? =) I'm all about breaking things into smaller pieces, as long as there's a simple cohesive way to weave them together in order to accomplish what we need. =)

> not everyone has to like everything.

I do like it. Please feel free to keep me informed of your progress. =)
