### ISSUE TITLE
add yolpo to the "Testing / Lint / Quality checkers" section

### ISSUE THREAD

**Issue by lorenzoongithub** [ericelliott/essential-javascript-links#34]
Hi Eric,
I would like to suggest the following link under  the "Testing / Lint / Quality checkers" section.

http://www.yolpo.com/ -  visual javascript interpreter in the browser for unmissable regression tests.

cheers,
lorenzo

**Comment by ericelliott** [comment]
Hi Lorenzo,

1. Yolpo is a non-starter for [universal JavaScript](https://medium.com/@mjackson/universal-javascript-4761051b7ae9) testing because it's a browser-dependent tool. In other words, it can't replace tools like Tape which offer quality CI error reporting via TAP output in Node. You should read [Why I Use Tape Instead of Mocha and So Should You](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4).
2. Yolpo would be very interesting to me for documentation and teaching if the source code was editable by the user in the iframe. People learn best when they're allowed to actually play with the code. Any plans to make the code editable in the iframe?

**Comment by lorenzoongithub** [comment]
Hi Eric,
1. Indeed yolpo is currently browser-tool, so it has limits  when compared to other tools.
2. You can already edit snippets of code on yolpo. 
For example you could go here http://www.yolpo.com/player/v.html?gist=d2d19a00747991285307&autoplay=2 and click on the pencil on the top right corner.
My bad the UI is far from obvious, but I will be working on it.
thanks and let me know if you find it useful
cheers

**Comment by ericelliott** [comment]
Is there any way to embed an example that is editable by default (no need for a pencil icon)?

**Comment by lorenzoongithub** [comment]
Hi Eric,
unfortunately not yet (I will work on it... but it won't be any time soon...). 
For now, If you want to embed an example you need to create a gist in github and refer to it on the yolpo's url.

p.s. are you going to add a link to yolpo ?

**Comment by ericelliott** [comment]
Not yet. Here's what you'll need to do to make it an essential resource:

* Make it easy to embed examples that are editable by default (I don't mind if they're sourced from a gist, as long as the user can easily edit them in the embedded yolpo).
* Make it easy to add libraries to the embed without making them part of the example. (i.e., React)
* Make sure to support ES6 (compile with babel).

Otherwise, it's a neat toy, but essentially worthless for any practical use.

**Comment by ericelliott** [comment]
One more thing... you'll want to position it as an interactive code example embed tool rather than a software testing tool, because its browser-dependent nature makes it worthless for testing universal JavaScript code. In other words, it can't compete with tools like Tape for unit testing that can integrate with CI/CD workflows.

If it's for testing, it's more of a toy than a tool.

If it's for code examples, it's a very cool tool. =)
